
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class AcademicSecurityRefund extends javax.swing.JFrame {

    /**
     * Creates new form AcademicSecurityRefund
     */
    public AcademicSecurityRefund() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsanno = new javax.swing.JTextField();
        txtpaidamount = new javax.swing.JTextField();
        txtrefamount = new javax.swing.JTextField();
        cmbrefmode = new javax.swing.JComboBox<>();
        cmbrefyear = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        cmbsanday = new javax.swing.JComboBox<>();
        cmbsanmonth = new javax.swing.JComboBox<>();
        cmbsanyear = new javax.swing.JComboBox<>();
        cmbrefpaid = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Academic Security Refund  Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 5, 440, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Sanction No.");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 75, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Sanction Date");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Paid Amount");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Refunded Amount");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Mode of Payment");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Refund Year");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 75, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Paid");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, 20));

        txtsanno.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(txtsanno, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 75, 168, -1));

        txtpaidamount.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(txtpaidamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, -1));

        txtrefamount.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(txtrefamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, -1));

        cmbrefmode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbrefmode.setForeground(new java.awt.Color(0, 102, 102));
        cmbrefmode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        getContentPane().add(cmbrefmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 135, -1));

        cmbrefyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbrefyear.setForeground(new java.awt.Color(0, 102, 102));
        cmbrefyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "1019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(cmbrefyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 72, 70, -1));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(0, 102, 102));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 294, 113, 40));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(0, 102, 102));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 112, 40));

        cmbsanday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbsanday.setForeground(new java.awt.Color(0, 102, 102));
        cmbsanday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbsanday, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        cmbsanmonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbsanmonth.setForeground(new java.awt.Color(0, 102, 102));
        cmbsanmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cmbsanmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        cmbsanyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbsanyear.setForeground(new java.awt.Color(0, 102, 102));
        cmbsanyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "1019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(cmbsanyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        cmbrefpaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbrefpaid.setForeground(new java.awt.Color(0, 102, 102));
        cmbrefpaid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(cmbrefpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 70, -1));

        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 102, 102));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbg1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 49, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        AcadLogin acl=new AcadLogin();
        acl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String sanno=txtsanno.getText();
        String sandate=cmbsanday.getSelectedItem()+"/"+cmbsanmonth.getSelectedItem()+"/"+cmbsanyear.getSelectedItem();
        String paidamount=txtpaidamount.getText();
        String refamount=txtrefamount.getSelectedText();
        String refmode=(String) cmbrefmode.getSelectedItem();
        String refyear=(String)cmbrefyear.getSelectedItem();
        String paid=(String)cmbrefpaid.getSelectedItem();
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/feeportal","root","password");
           if(con!=null)
             {
               Statement stmt = (Statement)con.createStatement();
                stmt.executeUpdate("insert into acadsecrefund(sanno,sandate,paidamount,refamount,refmode,paid) values('"+sanno+"','"+sandate+"','"+paidamount+"','"+refamount+"','"+refmode+"','"+paid+"')");
                JOptionPane.showMessageDialog(this,"Academic Refund Details added in Database Successfully" ,"Welldone!", 1);
             }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
           System.out.println("Exception Occured?");
           e.printStackTrace();
       }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtsanno.setText("");
        txtpaidamount.setText("");
        txtrefamount.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicSecurityRefund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicSecurityRefund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicSecurityRefund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicSecurityRefund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicSecurityRefund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> cmbrefmode;
    private javax.swing.JComboBox<String> cmbrefpaid;
    private javax.swing.JComboBox<String> cmbrefyear;
    private javax.swing.JComboBox<String> cmbsanday;
    private javax.swing.JComboBox<String> cmbsanmonth;
    private javax.swing.JComboBox<String> cmbsanyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtpaidamount;
    private javax.swing.JTextField txtrefamount;
    private javax.swing.JTextField txtsanno;
    // End of variables declaration//GEN-END:variables
}
