
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class SfpForm extends javax.swing.JFrame {

   Timer tm;
    int x=0;
    //images path in array
    String[] list={"D:\\NeatBeanProjects\\ StudentFeePortal\\src\\images\\home1.jpg",//0
                   "D:\\NeatBeanProjects\\ StudentFeePortal\\src\\images\\gbpec1.jpg",//1
                    "D:\\NeatBeanProjects\\ StudentFeePortal\\src\\images\\gbpec2.jpeg",//2
                    "D:\\NeatBeanProjects\\ StudentFeePortal\\src\\images\\home4.jpg",//3
                    "D:\\NeatBeanProjects\\ StudentFeePortal\\src\\images\\gbpec3.jpeg"//4
                    };
    public SfpForm() {
        super("Java SlideShow");
        initComponents();
        lblphoto.setBounds(40,30,700,300);
        //call the function setImageSize
        setImageSize(4);
        //set a timer
        tm=new Timer(2000,new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                setImageSize(x);
                x+=1;
                if(x>=list.length)
                {
                    x=0;
                }
            }
        }
        );
        tm.start();
        //setLayout(null);
        lblsfp.setOpaque(true);
        //lblsfp.setBackground(new Color(139,0,0));
        getContentPane().setBackground(new Color(204,204,255));
        //setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
   public void setImageSize(int i)
    {
        ImageIcon icon=new ImageIcon(list[i]);
        Image img=icon.getImage();
        Image newimg=img.getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newimc=new ImageIcon(newimg);
        lblphoto.setIcon(newimc);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsfp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnadmin = new javax.swing.JButton();
        btnacade = new javax.swing.JButton();
        btnacc = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsfp.setBackground(new java.awt.Color(153, 0, 0));
        lblsfp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblsfp.setForeground(new java.awt.Color(255, 255, 255));
        lblsfp.setText("Student Fee Portal");
        lblsfp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(0, 102, 102));
        btnadmin.setText("Admin Login");
        btnadmin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel2.add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, 55));

        btnacade.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnacade.setForeground(new java.awt.Color(0, 102, 102));
        btnacade.setText("Academic Login");
        btnacade.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnacade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacadeActionPerformed(evt);
            }
        });
        jPanel2.add(btnacade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 240, 56));

        btnacc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnacc.setForeground(new java.awt.Color(0, 102, 102));
        btnacc.setText("Accountant Login");
        btnacc.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccActionPerformed(evt);
            }
        });
        jPanel2.add(btnacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 250, 54));

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 102, 102));
        btncancel.setText("Cancel");
        btncancel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel2.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 450, 130, 30));

        lblphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home1.jpg"))); // NOI18N
        lblphoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lblsfp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsfp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnacadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacadeActionPerformed
        AcadLogin al=new AcadLogin();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnacadeActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        AdminLogin al=new AdminLogin();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnadminActionPerformed

    private void btnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccActionPerformed
         AccLogin al=new AccLogin();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnaccActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SfpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SfpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SfpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SfpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SfpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacade;
    private javax.swing.JButton btnacc;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncancel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblsfp;
    // End of variables declaration//GEN-END:variables
}
