/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtnadmin = new javax.swing.JRadioButton();
        rbtnacc = new javax.swing.JRadioButton();
        txtname = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        txtconpass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        passhint = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        txtsecque = new javax.swing.JTextField();
        rbtnacad = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Create Account");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText(" Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Contact No.");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 172, 150, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Password");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, 150, 30));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Confirm Password");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 302, 150, 30));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Email");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 222, 150, 30));

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Your\n Lucky\n Number");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 381, 150, 30));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("User");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        rbtnadmin.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rbtnadmin);
        rbtnadmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnadmin.setForeground(new java.awt.Color(255, 255, 255));
        rbtnadmin.setText("Admin");
        rbtnadmin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rbtnadmin.setName("adminrbtn"); // NOI18N
        rbtnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnadminActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 87, -1, 20));
        rbtnadmin.getAccessibleContext().setAccessibleName("adminrbtn");

        rbtnacc.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rbtnacc);
        rbtnacc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnacc.setForeground(new java.awt.Color(255, 255, 255));
        rbtnacc.setText("Accountant");
        rbtnacc.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rbtnacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnaccActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 87, -1, 20));

        txtname.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 102, 102));
        txtname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 220, 30));
        txtname.getAccessibleContext().setAccessibleName("txtname");

        txtcontact.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(0, 102, 102));
        txtcontact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 220, 30));

        txtemail.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemail.setForeground(new java.awt.Color(0, 102, 102));
        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 220, 30));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(0, 102, 102));
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 450, -1, -1));

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 102, 102));
        btncancel.setText("Cancel");
        btncancel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        txtpass.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 102, 102));
        txtpass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 220, 30));

        txtconpass.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtconpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtconpass.setForeground(new java.awt.Color(0, 102, 102));
        txtconpass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txtconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, 30));

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("PassWord Hint");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 342, 150, 30));

        passhint.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        passhint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passhint.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(passhint, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 220, 30));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreset.setForeground(new java.awt.Color(0, 102, 102));
        btnreset.setText("Reset");
        btnreset.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 450, -1, -1));

        txtsecque.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtsecque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsecque.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txtsecque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 220, 30));

        rbtnacad.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rbtnacad);
        rbtnacad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnacad.setForeground(new java.awt.Color(255, 255, 255));
        rbtnacad.setText("Academic");
        rbtnacad.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(rbtnacad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 87, -1, 20));

        jLabel10.setBackground(new java.awt.Color(153, 0, 51));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbg1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 480, 510));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 280, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    Statement stmt;
    ResultSet rs;
    static int count=1;
    ButtonGroup bg=new ButtonGroup();
    //bg.add(rbtnadmin);
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void rbtnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnaccActionPerformed

    private void rbtnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnadminActionPerformed
      
    }//GEN-LAST:event_rbtnadminActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        rbtnadmin.setActionCommand("Admin");
        rbtnacc.setActionCommand("Accountant");
        rbtnacad.setActionCommand("Acadmic");
        String user=buttonGroup1.getSelection().getActionCommand();
        String name=txtname.getText();
        String contact=txtcontact.getText();
        String email=txtemail.getText();
        char[] passchar=txtpass.getPassword();
        String pass=new String(passchar);
        char[] conpasschar=txtconpass.getPassword();
        String conpass=new String(conpasschar);
        String hint=passhint.getText();
        String secque=txtsecque.getText();
        if(user.equals("")||name.equals("")||contact.equals("")||pass.equals("")||conpass.equals("")||email.equals("")||hint.equals("")||secque.equals(""))
        {
                JOptionPane.showMessageDialog(null,"Please Fill all  fields first ","Warning?", 1);
        }
        else
        {
            String regex = "^([_a-zA-Z0-9-]+(.[_a-zA-Z0-9-]+)*@gmail.com)?$";
            String nmreg = "^[_a-zA-Z]+$";
                Pattern pattern = Pattern.compile(regex);
                Pattern pattern1 = Pattern.compile(nmreg);
                Matcher matcher = pattern.matcher(email);
                Matcher matcher1 = pattern1.matcher(name);
                   
                  if (!(matcher1.matches())) 
                    {
                        JOptionPane.showMessageDialog(null,"Your name is not valid ","Warning?", 1);
                    }
                    else
                    {
                        if (!matcher.matches()) 
                        {
                            JOptionPane.showMessageDialog(null,"Your Email is not valid ","Warning?", 1);
                        }
                        else
                        {   if(!pass.equals(conpass))
                            {
                                JOptionPane.showMessageDialog(null,"Your confirm password is not same as confirm password ","Warning?", 1);
                            }
                            else
                            {   
                            try
                            {
                                Class.forName("com.mysql.jdbc.Driver");
                                con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/feeportal","root","password");
                                if(con!=null)
                                {
                                        count++;
                                        String empid="SFP"+count;
                                        stmt=(Statement)con.createStatement();
                                        int s=stmt.executeUpdate("insert into signup(name,contactno,email,password,passhint,secque,userid,user) values('"+name+"','"+contact+"','"+email+"','"+pass+"','"+hint+"','"+secque+"','"+empid+"','"+user+"')");
                                        if(s>0)
                                        {
                                            JOptionPane.showMessageDialog(this,"SignUp Successfull\nYour EmpID:"+empid ,"Welldone!", 1);
                                        }
                                }
                             }
                            catch(Exception e)
                            {
                                JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
                                System.out.println("Exception Occured?");
                                e.printStackTrace();
                            } 
                          }
                        }
                    }
            } 
         txtname.setText("");
        txtcontact.setText("");
        txtemail.setText("");
        txtpass.setText("");
        txtconpass.setText("");
        passhint.setText("");
        txtsecque.setText("");
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
       this.setVisible(false);
       //count++;
       //System.out.println(count);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtname.setText("");
        txtcontact.setText("");
        txtemail.setText("");
        txtpass.setText("");
        txtconpass.setText("");
        passhint.setText("");
        txtsecque.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passhint;
    private javax.swing.JRadioButton rbtnacad;
    private javax.swing.JRadioButton rbtnacc;
    private javax.swing.JRadioButton rbtnadmin;
    private javax.swing.JPasswordField txtconpass;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtsecque;
    // End of variables declaration//GEN-END:variables
}
