
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class StudentReports extends javax.swing.JFrame {

    /**
     * Creates new form StudentReports
     */
    public StudentReports() {
        initComponents();
        showUser();
    }
     public ArrayList<User1> userList()
    {
        ArrayList<User1> userList= new ArrayList<>();
         try
        {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/feeportal","root","password");
           if(con!=null)
             {
               Statement stmt = (Statement)con.createStatement();
               ResultSet rs = stmt.executeQuery("select * from student");
               User1 user1;
                while(rs.next())
                {
                    
                        user1 = new User1(rs.getString("rollno"),rs.getString("sname"),rs.getString("dob"),rs.getString("course"),
                                rs.getString("branch"),rs.getString("sem"),rs.getString("cetrank"),rs.getString("email"),rs.getString("contactno"),rs.getString("gender"),rs.getString("address"));
                        userList.add(user1);
            
                }
             }
       }
       catch(Exception e)
       {
           System.out.println("Exception Occured?");
           e.printStackTrace();
       }
        return userList;
    } 
    public void showUser()
    {
        ArrayList<User1> list=userList();
        DefaultTableModel model=(DefaultTableModel) stutable.getModel();
        Object[] row=new Object[11];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getrollno();
            row[1]=list.get(i).getsname();
            row[2]=list.get(i).getdob();
            row[3]=list.get(i).getcourse();
            row[4]=list.get(i).getbranch();
            row[5]=list.get(i).getsem();
            row[6]=list.get(i).getcetrank();
            row[7]=list.get(i).getemail();
            row[8]=list.get(i).getcontact();
            row[9]=list.get(i).getgender();
            row[10]=list.get(i).getadrs();
            model.addRow(row);
        }
    }
    public ArrayList<User1> userList1()
    {
        ArrayList<User1> userList1= new ArrayList<>();
        String br=(String) cmbbr.getSelectedItem();
        String year=(String) cmbyear.getSelectedItem();
        String cat=(String) cmbcategory.getSelectedItem();
        String gender=(String) cmbgender.getSelectedItem();
         try
        {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/feeportal","root","password");
           if(con!=null)
             {
               Statement stmt = (Statement)con.createStatement();
               ResultSet rs = stmt.executeQuery("select * from student where branch='"+br+"' AND sem='"+year+"'AND catagory='"+cat+"'AND sem='"+gender+"'");
               User1 user1;
                while(rs.next())
                {
                    
                        user1 = new User1(rs.getString("rollno"),rs.getString("sname"),rs.getString("dob"),rs.getString("course"),
                                rs.getString("branch"),rs.getString("sem"),rs.getString("cetrank"),rs.getString("email"),rs.getString("contactno"),rs.getString("gender"),rs.getString("address"));
                        userList1.add(user1);
            
                }
             }
       }
       catch(Exception e)
       {
           System.out.println("Exception Occured?");
           e.printStackTrace();
       }
        return userList1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stutable = new javax.swing.JTable();
        btnstulist = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cmbbr = new javax.swing.JComboBox<>();
        cmbyear = new javax.swing.JComboBox<>();
        cmbcategory = new javax.swing.JComboBox<>();
        cmbgender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stutable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stutable.setForeground(new java.awt.Color(0, 102, 102));
        stutable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Sname", "DOB", "Course", "Branch", "Year", "Cet Rank", "Email", "Contact No", "Gender", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        stutable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stutableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stutable);

        btnstulist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnstulist.setForeground(new java.awt.Color(0, 102, 102));
        btnstulist.setText("Sort Reports");
        btnstulist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstulistActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 102, 102));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 102, 102));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        cmbbr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbbr.setForeground(new java.awt.Color(0, 102, 102));
        cmbbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRANCH", "CSE", "ECE", "MAE" }));

        cmbyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbyear.setForeground(new java.awt.Color(0, 102, 102));
        cmbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "FIRSTYEAR", "SECONDYEAR", "THIRDYEAR", "FINALYEAR" }));

        cmbcategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbcategory.setForeground(new java.awt.Color(0, 102, 102));
        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORY", "GEN", "OBC", "SC/ST", "OTHER" }));

        cmbgender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbgender.setForeground(new java.awt.Color(0, 102, 102));
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENDER", "MALE", "FEMALE" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbbr, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnstulist, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncancel)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstulist, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel)
                    .addComponent(btnback)
                    .addComponent(cmbbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        AdminForm af=new AdminForm();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnstulistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstulistActionPerformed
        ArrayList<User1> list=userList1();
        DefaultTableModel model=(DefaultTableModel) stutable.getModel();
        Object[] row=new Object[11];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getrollno();
            row[1]=list.get(i).getsname();
            row[2]=list.get(i).getdob();
            row[3]=list.get(i).getcourse();
            row[4]=list.get(i).getbranch();
            row[5]=list.get(i).getsem();
            row[6]=list.get(i).getcetrank();
            row[7]=list.get(i).getemail();
            row[8]=list.get(i).getcontact();
            row[9]=list.get(i).getgender();
            row[10]=list.get(i).getadrs();
            model.addRow(row);
        }
    }//GEN-LAST:event_btnstulistActionPerformed

    private void stutableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stutableMouseClicked
      StudentInformation si=new StudentInformation();
      int index=stutable.getSelectedRow();
      TableModel tmodel=stutable.getModel();
      String rollno=tmodel.getValueAt(index,0).toString();
      String sname=tmodel.getValueAt(index,1).toString();
      String dob=tmodel.getValueAt(index,2).toString();
      String course=tmodel.getValueAt(index,3).toString();
      String branch=tmodel.getValueAt(index,4).toString();
      String year=tmodel.getValueAt(index,5).toString();
      String cetrank=tmodel.getValueAt(index,6).toString();
      String email=tmodel.getValueAt(index,7).toString();
      String contact=tmodel.getValueAt(index,8).toString();
      String gender=tmodel.getValueAt(index,9).toString();
      String address=tmodel.getValueAt(index,10).toString();
      if(!rollno.equals("")||!sname.equals("")||!dob.equals("")||!course.equals("")||!branch.equals("")||!year.equals("")||!cetrank.equals("")||!email.equals("")||!contact.equals("")||!gender.equals("")||!address.equals(""))
            {
                si.setVisible(true);
                si.txtroll.setText(rollno);
                si.txtsname.setText(sname);
                si.txtdob.setText(dob);
                si.txtcourse.setText(course);
                si.txtbranch.setText(branch);
                si.txtyear.setText(year);
                si.txtrank.setText(cetrank);
                si.txtemail.setText(email);
                si.txtcontact.setText(contact);
                si.txtgender.setText(gender);
                si.txtadrs.setText(address);
                this.setVisible(false);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_stutableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnstulist;
    private javax.swing.JComboBox<String> cmbbr;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbyear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stutable;
    // End of variables declaration//GEN-END:variables
}
